 var Imagenes = new Array();

Imagenes["nvVoii"] = {}
Imagenes["nvVoii"].src = '../../FW/image/icons/nvVoii.png';
Imagenes["nv_admin"] = {}
Imagenes["nv_admin"].src = '../../FW/image/sistemas/nv_admin.png';
Imagenes["nv_mutual"] = {}
Imagenes["nv_mutual"].src = '../../FW/image/sistemas/nv_mutual.png';
Imagenes["nv_rrhh"] = {}
Imagenes["nv_rrhh"].src = '../../FW/image/sistemas/nv_rrhh.png';
Imagenes["nv_wiki"] = {}
Imagenes["nv_wiki"].src = '../../FW/image/sistemas/nv_wiki.png';
Imagenes["nv_diario"] = {}
Imagenes["nv_diario"].src = '../../FW/image/sistemas/nv_diario.png';
Imagenes["nv_control_lavado"] = {}
Imagenes["nv_control_lavado"].src = '../../FW/image/sistemas/nv_control_lavado.png';
Imagenes["nv_tarjeta"] = {}
Imagenes["nv_tarjeta"].src = '../../FW/image/sistemas/nv_tarjeta.png';
Imagenes["admintenelohoy"] = {}
Imagenes["admintenelohoy"].src = '../../FW/image/sistemas/nv_tenelohoy.png';
//----------------------------CUAD----------------------------------///
Imagenes["mensajes"] = {}
Imagenes["mensajes"].src = '../../FW/image/icons/mensajes.png'Imagenes['inf'] = new Image();
                Imagenes['inf'].src = '/FW/image/transferencia/file_inf.png';
                Imagenes['exp'] = new Image();
                Imagenes['exp'].src = '/FW/image/transferencia/file_exp.png';
                Imagenes['dts'] = new Image();
                Imagenes['dts'].src = '/FW/image/transferencia/file_dts.png';
                Imagenes['scr'] = new Image();
                Imagenes['scr'].src = '/FW/image/transferencia/file_scr.png';
                Imagenes['sp'] = new Image();
                Imagenes['sp'].src = '/FW/image/transferencia/file_sp.png';
                Imagenes['xls'] = new Image();
                Imagenes['xls'].src = '/FW/image/transferencia/file_xls.png';
                Imagenes['ssr'] = new Image();
                Imagenes['ssr'].src = '/FW/image/transferencia/file_ssr.png';
                Imagenes['eqv'] = new Image();
                Imagenes['eqv'].src = '/FW/image/transferencia/file_eqv.png';
                Imagenes['usr'] = new Image();
                Imagenes['usr'].src = '/FW/image/transferencia/file_usr.png';
                Imagenes['var'] = new Image();
                Imagenes['var'].src = '/FW/image/transferencia/file_variable.png';
                Imagenes['and'] = new Image();
                Imagenes['and'].src = '/FW/image/transferencia/file_AND.png';
                Imagenes['or'] = new Image();
                Imagenes['or'].src = '/FW/image/transferencia/file_OR.png';
                Imagenes['xor'] = new Image();
                Imagenes['xor'].src = '/FW/image/transferencia/file_XOR.png';
                Imagenes['ini'] = new Image();
                Imagenes['ini'].src = '/FW/image/transferencia/file_INI.png';
                Imagenes['ius'] = new Image();
                Imagenes['ius'].src = '/FW/image/transferencia/file_IUS.png';
                Imagenes['end'] = new Image();
                Imagenes['end'].src = '/FW/image/transferencia/file_END.png';
                Imagenes['ene'] = new Image();
                Imagenes['ene'].src = '/FW/image/transferencia/file_ENE.png';
                Imagenes['event'] = new Image();
                Imagenes['event'].src = '/FW/image/transferencia/file_EVE.png';
                Imagenes['timer'] = new Image();
                Imagenes['timer'].src = '/FW/image/transferencia/file_TMR.png';
                Imagenes['timer_inicio'] = new Image();
                Imagenes['timer_inicio'].src = '/FW/image/transferencia/file_TII.png';
                Imagenes['msg'] = new Image();
                Imagenes['msg'].src = '/FW/image/transferencia/file_MSG.png';
                Imagenes['pool'] = new Image();
                Imagenes['pool'].src = '/FW/image/transferencia/file_POOL.png';
                Imagenes['lane'] = new Image();
                Imagenes['lane'].src = '/FW/image/transferencia/file_LANE.png';
                Imagenes['annotation'] = new Image();
                Imagenes['annotation'].src = '/FW/image/transferencia/annotation.png';
                Imagenes['pdf'] = new Image();
                Imagenes['pdf'].src = '/FW/image/icons/file_pdf.png';
                Imagenes['html'] = new Image();
                Imagenes['html'].src = '/FW/image/icons/file_markup.png';
Imagenes["movimientos"] = {}
Imagenes["movimientos"].src = '../../FW/image/icons/movimientos.png'
//----------------------------CUAD----------------------------------///

Imagenes["permiso_asignado"] = {}
Imagenes["permiso_asignado"].src = '../../FW/image/icons/user_add.png';
Imagenes["permiso_sin_asignar"] = {}
Imagenes["permiso_sin_asignar"].src = '../../FW/image/icons/user_delete2.png';
Imagenes["arbol"] = {}
Imagenes["arbol"].src = '../../FW/image/icons/arbol.png';
Imagenes["adjuntar"] = {}
Imagenes["adjuntar"].src = '../../FW/image/icons/adjuntar.png';
Imagenes["filtro"] = {}
Imagenes["filtro"].src = '../../FW/image/icons/filtro.png'
Imagenes["clave"] = {}
Imagenes["clave"].src = '../../FW/image/icons/clave.png'
Imagenes["pendientes"] = {}
Imagenes["pendientes"].src = '../../FW/image/icons/reporte.gif';
Imagenes["reporte1"] = {}
Imagenes["reporte1"].src = '../../FW/image/icons/reporte.gif';
Imagenes["help"] = {}
Imagenes["help"].src = '../../FW/image/icons/help.gif';
Imagenes["persona"] = {}
Imagenes["persona"].src = '../../FW/image/icons/user.gif';
Imagenes["imprimir"] = {}
Imagenes["imprimir"].src = '../../FW/image/icons/print2.gif';
Imagenes["credito"] = {}
Imagenes["credito"].src = '../../FW/image/icons/credito.gif';
Imagenes["credito1"] = {}
Imagenes["credito1"].src = '../../FW/image/icons/Dollar.png';
Imagenes["credito_editar"] = {}
Imagenes["credito_editar"].src = '../../FW/image/icons/credito_editar.gif';
Imagenes["credito_mas"] = {}
Imagenes["credito_mas"].src = '../../FW/image/icons/credito_mas.gif';
Imagenes["persona_cambiar_id"] = {}
Imagenes["persona_cambiar_id"].src = '../../FW/image/icons/persona_cambiar_id.gif';
Imagenes["persona_descuentos"] = {}
Imagenes["persona_descuentos"].src = '../../FW/image/icons/coins_delete.png';
Imagenes["mail"] = {}
Imagenes["mail"].src = '../../FW/image/icons/mail.gif';
Imagenes["credito_propiedades"] = {}
Imagenes["credito_propiedades"].src = '../../FW/image/icons/propiedades.png';
Imagenes["legajo_editar"] = {}
Imagenes["legajo_editar"].src = '../../FW/image/icons/legajo_editar.png';
Imagenes["comentario"] = {}
Imagenes["comentario"].src = '../../FW/image/icons/comentario3.png';
Imagenes["operador"] = {}
Imagenes["operador"].src = '../../FW/image/icons/operador.png';
Imagenes["activedirectory"] = {}
Imagenes["activedirectory"].src = '../../FW/image/icons/activedirectory.png';
Imagenes["seguro"] = {}
Imagenes["seguro"].src = '../../FW/image/icons/seguro.png';
Imagenes["mov_credito"] = {}
Imagenes["mov_credito"].src = '../../FW/image/icons/mov_credito.png';
Imagenes["recupero"] = {}
Imagenes["recupero"].src = '../../FW/image/icons/recupero.png';
Imagenes["legajo"] = {}
Imagenes["legajo"].src = '../../FW/image/icons/legajo.png';
Imagenes["canal"] = {}
Imagenes["canal"].src = '../../FW/image/icons/canal.png';
Imagenes["guia_tel"] = {}
Imagenes["guia_tel"].src = '../../FW/image/icons/guia_tel.png';
Imagenes["abm"] = {}
Imagenes["abm"].src = '../../FW/image/icons/abm.png';
Imagenes["guardar"] = {}
Imagenes["guardar"].src = '../../FW/image/icons/guardar.png';
Imagenes["guardar_como"] = {}
Imagenes["guardar_como"].src = '../../FW/image/icons/guardar_como.png';
Imagenes["foto"] = {}
Imagenes["foto"].src = '../../FW/image/icons/foto.png';
Imagenes["cuenta_mas"] = {}
Imagenes["cuenta_mas"].src = '../../FW/image/icons/cuenta_mas.gif';
Imagenes["seleccionar"] = {}
Imagenes["seleccionar"].src = '../../FW/image/icons/agregar_cargo.png';
Imagenes["persona_seleccionar"] = {}
Imagenes["persona_seleccionar"].src = '../../FW/image/icons/persona_seleccionar.gif';
Imagenes["plan_sel"] = {}
Imagenes["plan_sel"].src = '../../FW/image/icons/plan_seleccionar1.gif';
Imagenes["persona_sel"] = {}
Imagenes["persona_sel"].src = '../../FW/image/icons/persona_seleccionar.gif';
Imagenes["persona_quitar"] = {}
Imagenes["persona_quitar"].src = '../../FW/image/icons/persona_quitar.gif';
Imagenes["descuento_saldo"] = {}
Imagenes["descuento_saldo"].src = '../../FW/image/icons/descuento_saldo.gif';
Imagenes["descuento_mas"] = {}
Imagenes["descuento_mas"].src = '../../FW/image/icons/descuento_mas.gif';
Imagenes["procesos"] = {}
Imagenes["procesos"].src = '../../FW/image/icons/procesos.gif';
Imagenes["servidor"] = {}
Imagenes["servidor"].src = '../../FW/image/icons/servidor.png';
Imagenes["sistema"] = {}
Imagenes["sistema"].src = '../../FW/image/sistemas/sistema.png';
Imagenes["rh_buscar"] = {}
Imagenes["rh_buscar"].src = '../../FW/image/icons/buscar.png';
Imagenes["password"] = {}
Imagenes["password"].src = '../../FW/image/icons/candado.png';
Imagenes["folder"] = {}
Imagenes["folder"].src = '../../FW/image/icons/folder.png';
Imagenes["cancelar"] = {}
Imagenes["cancelar"].src = '../../FW/image/icons/cancelar.png';
Imagenes["servicio"] = {}
Imagenes["servicio"].src = '../../FW/image/icons/servicio.png';
Imagenes["servicio_buscar"] = {}
Imagenes["servicio_buscar"].src = '../../FW/image/icons/servicio_buscar.png';
Imagenes["servicio_asignar"] = {}
Imagenes["servicio_asignar"].src = '../../FW/image/icons/servicio_asignar.png';
Imagenes["plan"] = {}
Imagenes["plan"].src = '../../FW/image/icons/plan.png';
Imagenes["entidad"] = {}
Imagenes["entidad"].src = '../../FW/image/icons/entidad.png';
Imagenes["entidad_grupo"] = {}
Imagenes["entidad_grupo"].src = '../../FW/image/icons/entidad_grupo.png';
Imagenes["cheque"] = {}
Imagenes["cheque"].src = '../../FW/image/icons/cheque.png';
Imagenes["nota_revision"] = {}
Imagenes["nota_revision"].src = '../../FW/image/icons/nota_revision.png';
Imagenes["nota_inspeccion"] = {}
Imagenes["nota_inspeccion"].src = '../../FW/image/icons/servicio_buscar.png';
Imagenes["edicion"] = {}
Imagenes["edicion"].src = '../../FW/image/icons/edicion.png';
Imagenes["publicacion"] = {}
Imagenes["publicacion"].src = '../../FW/image/icons/publicacion.png';
Imagenes["cambio_estado"] = {}
Imagenes["cambio_estado"].src = '../../FW/image/icons/cambio_estado.png';
Imagenes["parametros"] = {}
Imagenes["parametros"].src = '../../FW/image/icons/parametros.png';

Imagenes['estructura'] = {}
Imagenes['estructura'].src = '../../FW/image/icons/tree.gif';
Imagenes['indice'] = {}
Imagenes['indice'].src = '../../FW/image/icons/tree.gif';
Imagenes['buscar'] = {}
Imagenes['buscar'].src = '../../FW/image/icons/buscar.png';
Imagenes['cerrar'] = {}
Imagenes['cerrar'].src = '../../FW/image/icons/eliminar.png';
Imagenes['trabajo'] = {}
Imagenes['trabajo'].src = '../../FW/image/icons/trabajo.png';
Imagenes['empresa'] = {}
Imagenes['empresa'].src = '../../FW/image/icons/empresa.png';
Imagenes['sector'] = {}
Imagenes['sector'].src = '../../FW/image/icons/sector.png';
Imagenes['ref'] = {}
Imagenes['ref'].src = '../../FW/image/icons/info.png';
Imagenes['actualizar'] = {}
Imagenes['actualizar'].src = '../../FW/image/icons/refresh.png';
Imagenes['pagina_impresion'] = {}
Imagenes['pagina_impresion'].src = '../../FW/image/icons/pagina_impresion.png';
Imagenes['exit'] = {}
Imagenes['exit'].src = '../../FW/image/icons/exit.png';
Imagenes['subir'] = {}
Imagenes['subir'].src = '../../FW/image/icons/subir.png';
Imagenes['bajar'] = {}
Imagenes['bajar'].src = '../../FW/image/icons/bajar.png';
Imagenes['eliminar'] = {}
Imagenes['eliminar'].src = '../../FW/image/icons/eliminar.png';
Imagenes['agregar1'] = {}
Imagenes['agregar1'].src = '../../FW/image/icons/agregar.png';
Imagenes['cuenta'] = {}
Imagenes['cuenta'].src = '../../FW/image/icons/cuenta.png';
Imagenes["periodo"] = {}
Imagenes["periodo"].src = '../../FW/image/icons/periodo.png';
Imagenes["abierto"] = {}
Imagenes["abierto"].src = '../../FW/image/icons/abierto.png';
Imagenes["cerrado"] = {}
Imagenes["cerrado"].src = '../../FW/image/icons/cerrar.png';
Imagenes['ayuda'] = {}
Imagenes['ayuda'].src = '../../FW/image/icons/ayuda.png';
Imagenes['default'] = {}
Imagenes['default'].src = '../../FW/image/icons/user.gif';
Imagenes['hoja'] = {}
Imagenes['hoja'].src = '../../FW/image/icons/nueva.png';
Imagenes['Desconocida'] = {}
Imagenes['Desconocida'].src = '../../FW/image/icons/user.gif';

Imagenes['registro'] = {}
Imagenes['registro'].src = '../../FW/image/icons/registro.gif';
Imagenes['registro_mas'] = {}
Imagenes['registro_mas'].src = '../../FW/image/icons/registro_mas.gif';
Imagenes['registro_mas2'] = {}
Imagenes['registro_mas2'].src = '../../FW/image/icons/registro_mas2.gif';
Imagenes['registro_editar'] = {}
Imagenes['registro_editar'].src = '../../FW/image/icons/registro_editar.gif';
Imagenes['down'] = {}
Imagenes['down'].src = '../../FW/image/icons/down.gif';
Imagenes['up'] = {}
Imagenes['up'].src = '../../FW/image/icons/up.gif';
Imagenes['upload'] = {}
Imagenes['upload'].src = '../../FW/image/icons/upload.png';

Imagenes['carta'] = {}
Imagenes['carta'].src = '../../FW/image/icons/script.png';
Imagenes['analisis'] = {}
Imagenes['analisis'].src = '../../FW/image/icons/analisis.png';
Imagenes['catalogo'] = {}
Imagenes['catalogo'].src = '../../FW/image/icons/Catalogo.gif';
Imagenes['agregar'] = {}
Imagenes['agregar'].src = '../../FW/image/icons/seleccionar.gif';
Imagenes['modulo'] = {}
Imagenes['modulo'].src = '../../FW/image/icons/modulo.png';
Imagenes['login'] = {}
Imagenes['login'].src = '../../FW/image/icons/login.png';
Imagenes['permiso'] = {}
Imagenes['permiso'].src = '../../FW/image/icons/permiso.png';


 Imagenes["interbanking"] = {}
 Imagenes["interbanking"].src = '../../FW/image/icons/interbanking.png';
 Imagenes["inicio"] = {}
 Imagenes["inicio"].src = '../../FW/image/icons/home.png';
 Imagenes['herramientas'] = {}
 Imagenes['herramientas'].src = '../../FW/image/icons/herramientas.png';
 Imagenes["adminreporte"] = {}
 Imagenes["adminreporte"].src = '../../FW/image/icons/adminreporte.png';
 Imagenes["reporte"] = {}
 Imagenes["reporte"].src = '../../FW/image/icons/reporte.png';
 Imagenes["comb_pendientes"] = {}
 Imagenes["comb_pendientes"].src = '../../FW/image/icons/comprobantes_pendientes.png';
 Imagenes["procesar"] = {}
 Imagenes["procesar"].src = '../../FW/image/icons/procesar.png';
 Imagenes["envios"] = {}
 Imagenes["envios"].src = '../../FW/image/icons/envios.png';
 Imagenes["envios_finalizados"] = {}
 Imagenes["envios_finalizados"].src = '../../FW/image/icons/envios_finalizados.png';
 Imagenes["envios_pendientes"] = {}
 Imagenes["envios_pendientes"].src = '../../FW/image/icons/envios_pendientes.png';
 Imagenes["pagos"] = {}
 Imagenes["pagos"].src = '../../FW/image/icons/pagos.png';
 Imagenes["pagos1"] = {}
 Imagenes["pagos1"].src = '../../FW/image/icons/pagos1.png';
 Imagenes["pagos2"] = {}
 Imagenes["pagos2"].src = '../../FW/image/icons/money_add.png';
 Imagenes["pago_voluntario"] = {}
 Imagenes["pago_voluntario"].src = '../../FW/image/icons/pago_voluntario.png';
 Imagenes["tablas"] = {}
 Imagenes["tablas"].src = '../../FW/image/icons/tablas.png';
 Imagenes["persona_sel"] = {}
 Imagenes["persona_sel"].src = '../../FW/image/icons/personas.png';
 Imagenes['modulo'] = {}
 Imagenes['modulo'].src = '../../FW/image/icons/modulo.png';
 Imagenes["editar"] = {}
 Imagenes["editar"].src = '../../FW/image/icons/editar.png';
 Imagenes["buscar_doc"] = {}
 Imagenes["buscar_doc"].src = '../../FW/image/icons/buscar_doc.png';
 Imagenes["socio"] = {}
 Imagenes["socio"].src = '../../FW/image/icons/socio.png';
 Imagenes["socio_alta"] = {}
 Imagenes["socio_alta"].src = '../../FW/image/icons/socio_alta.png';
 Imagenes["socio_baja"] = {}
 Imagenes["socio_baja"].src = '../../FW/image/icons/socio_baja.png';
 Imagenes["periodicidad"] = {}
 Imagenes["periodicidad"].src = '../../FW/image/icons/periodicidad.png';
 Imagenes["excel"] = {}
 Imagenes["excel"].src = '../../FW/image/icons/excel.png';
 Imagenes["pdf"] = {}
 Imagenes["pdf"].src = '../../FW/image/icons/file_pdf.png';
 
 Imagenes["mas"] = {}
 Imagenes["mas"].src = '../../FW/image/icons/mas.jpg';
 Imagenes["menos"] = {}
 Imagenes["menos"].src = '../../FW/image/icons/menos.jpg';
 Imagenes["punto"] = {}
 Imagenes["punto"].src = '../../FW/image/icons/punto.jpg';
 Imagenes["persona_mas"] = {}
 Imagenes["persona_mas"].src = '../../FW/image/icons/persona_mas.gif';
 Imagenes["persona_editar"] = {}
 Imagenes["persona_editar"].src = '../../FW/image/icons/persona_editar.gif';
 Imagenes["imprimir"] = {}
 Imagenes["imprimir"].src = '../../FW/image/icons/imprimir.png';
 Imagenes["printer"] = {}
 Imagenes["printer"].src = '../../FW/image/icons/printer.png';
 Imagenes['nueva'] = {}
 Imagenes['nueva'].src = '../../FW/image/icons/nueva.png';
 Imagenes['browser_img'] = {}
 Imagenes['browser_img'].src = '../../FW/image/icons/browser_img.png';
 Imagenes['explorer'] = {}
 Imagenes['explorer'].src = '../../FW/image/icons/explorer.png';
 Imagenes['cable'] = {}
 Imagenes['cable'].src = '../../FW/image/icons/download_txt.png';
 
 Imagenes["hoy"] = {}
 Imagenes["hoy"].src = '../../FW/image/icons/hoy.png';
 Imagenes["dia"] = {}
 Imagenes["dia"].src = '../../FW/image/icons/dia.png';
 Imagenes["semana"] = {}
 Imagenes["semana"].src = '../../FW/image/icons/semana.png';
 Imagenes["mes"] = {}
 Imagenes["mes"].src = '../../FW/image/icons/mes.png';
 Imagenes['contactos'] = {}
 Imagenes['contactos'].src = '../../FW/image/icons/contactos2.ico';
 Imagenes["telefono01"] = {}
 Imagenes["telefono01"].src = '../../FW/image/icons/telefono2.png'; 
  
 Imagenes["vincular"] = {}
 Imagenes["vincular"].src = '../../FW/image/icons/vincular.png';
 Imagenes["desvincular"] = {}
 Imagenes["desvincular"].src = '../../FW/image/icons/desvincular.png';
 
 Imagenes["trabajo_mas"] = {}
 Imagenes["trabajo_mas"].src = '../../FW/image/icons/trabajo_mas.gif';
 Imagenes["trabajo"] = {}
 Imagenes["trabajo"].src = '../../FW/image/icons/trabajo.png';
 Imagenes["bica"] = {}
 Imagenes["bica"].src = '../../FW/image/icons/bica.png';
 Imagenes["abm1"] = {}
 Imagenes["abm1"].src = '../../FW/image/icons/abm1.png';
 Imagenes["bejerman"] = {}
 Imagenes["bejerman"].src = '../../FW/image/icons/bejerman.png';
 Imagenes["bloqueo"] = {}
 Imagenes["bloqueo"].src = '../../FW/image/icons/bloqueo.png';
 Imagenes["mapa"] = {}
 Imagenes["mapa"].src = '../../FW/image/icons/mapa_ico.gif';
 Imagenes["libro"] = {}
 Imagenes["libro"].src = '../../FW/image/icons/libro.png';
 Imagenes["persona_add"] = {}
 Imagenes["persona_add"].src = '../../FW/image/icons/user_add.png';
 Imagenes["persona_edit"] = {}
 Imagenes["persona_edit"].src = '../../FW/image/icons/user_edit.png';
 Imagenes["persona_go"] = {}
 Imagenes["persona_go"].src = '../../FW/image/icons/user_go.png';
 Imagenes["cobro"] = {}
 Imagenes["cobro"].src = '../../FW/image/icons/coins_in_hand.png';
 Imagenes["cta_banco"] = {}
 Imagenes["cta_banco"].src = '../../FW/image/icons/bank.png';
 Imagenes["estado"] = {}
 Imagenes["estado"].src = '../../FW/image/icons/folder_go.png';
 Imagenes["control_calidad"] = {}
 Imagenes["control_calidad"].src = '../../FW/image/icons/control_calidad.png';
 Imagenes["cobranzas"] = {}
 Imagenes["cobranzas"].src = '../../FW/image/icons/business.gif';
 Imagenes["muper"] = {}
 Imagenes["muper"].src = '../../FW/image/icons/logo_muper.png';
 Imagenes['auto_run'] = {}
 Imagenes['auto_run'].src = '../../FW/image/icons/auto_run.png';

 //LINKS a otras aplicaciones 
 Imagenes['sidecreer'] = {}
 Imagenes['sidecreer'].src = '../../FW/image/icons/links/sidecreer16x16.png'
 Imagenes['anses'] = {}
 Imagenes['anses'].src = '../../FW/image/icons/links/anses.png'
 Imagenes['telecom'] = {}
 Imagenes['telecom'].src = '../../FW/image//icons/links/telecom.png'
 Imagenes['nosis'] = {}
 Imagenes['nosis'].src = '../../FW/image/icons/links/nosis.png'
 Imagenes['bcra'] = {}
 Imagenes['bcra'].src = '../../FW/image/icons/links/bcra.png'
 Imagenes['ie'] = {}
 Imagenes['ie'].src = '../../FW/image/icons/links/ie.png'
 
 //wiki tarea
 
 Imagenes['period_origen'] = {}
 Imagenes['period_origen'].src = '../../FW/image/icons/periodicidad_origen.png';
 Imagenes['guardar_cerrar'] = {}
 Imagenes['guardar_cerrar'].src = '../../FW/image/icons/guardar_cerrar.png';
 Imagenes['play'] = {}
 Imagenes['play'].src = '../../FW/image/icons/play.png';
 
  //Diario

 Imagenes['comprobante'] = {}
 Imagenes['comprobante'].src = '../../FW/image/icons/modulo2.ico';
 Imagenes['factura'] = {}
 Imagenes['factura'].src = '../../FW/image/icons/guita.ico';
 Imagenes['contacto'] = {}
 Imagenes['contacto'].src = '../../FW/image/icons/grupo.png';
 Imagenes['confirmar'] = {}
 Imagenes['confirmar'].src = '../../FW/image/icons/confirmar.png';
 Imagenes['nuevo'] = {}
 Imagenes['nuevo'].src = '../../FW/image/icons/file.png';
 Imagenes["editar_rubro"] = {}
 Imagenes["editar_rubro"].src = '../../FW/image/icons/edit-3.ico';
 Imagenes["eliminar_rubro"] = {}
 Imagenes["eliminar_rubro"].src = '../../FW/image/icons/eliminar1.png'
 Imagenes["anular_comprobante"] = {}
 Imagenes["anular_comprobante"].src = '../../FW/image/icons/sinlegajo1.png'
 Imagenes['copiar'] = {}
 Imagenes['copiar'].src = '../../FW/image/icons/copiar.png';
 
 
 //Lavado
 Imagenes["alerta"] = {}
 Imagenes["alerta"].src = '../../FW/image/icons/alerta.png';
 
 
 //RRHH 
Imagenes["imprimir2"] = {}
Imagenes["imprimir2"].src = '../../FW/image/icons/imprimir.png';
Imagenes["asignar"] = {}
Imagenes["asignar"].src = '../../FW/image/icons/asignar.png';
Imagenes["confirmar"] = {}
Imagenes["confirmar"].src = '../../FW/image/icons/activo.png';
Imagenes["confirmar_det"] = {}
Imagenes["confirmar_det"].src = '../../FW/image/icons/agregar_cargo.png';
Imagenes["agregar_novedad"] = {}
Imagenes["agregar_novedad"].src = '../../FW/image/icons/agregar_novedad.png';


//SICA
Imagenes["dependencia"] = {}
Imagenes["dependencia"].src = '../../FW/image/icons/agregar_novedad.png';
Imagenes['script'] = {}
Imagenes['script'].src = '../../FW/image/icons/script.png';
Imagenes["pasajes"] = {}
Imagenes["pasajes"].src = '../../FW/image/icons/modulo5.ico';
Imagenes["aplicarCambios"] = {}
Imagenes["aplicarCambios"].src = '../../FW/image/icons/abierto1.png';
Imagenes["asignarModulo"] = {}
Imagenes["asignarModulo"].src = '../../FW/image/icons/asignar.png';
Imagenes["genPasaje"] = {}
Imagenes["genPasaje"].src = '../../FW/image/icons/arbol.ico';
Imagenes["controlInteg"] = {}
Imagenes["controlInteg"].src = '../../FW/image/icons/control_calidad.png';
Imagenes["exportar"] = {}
Imagenes["exportar"].src = '../../FW/image/icons/bajar.png';
Imagenes["importar"] = {}
Imagenes["importar"].src = '../../FW/image/icons/returndoc.gif';
Imagenes["pasaje_dependencia"] = {}
Imagenes["pasaje_dependencia"].src = '../../FW/image/icons/planes.gif';


