 var Imagenes = new Array();

Imagenes["nvVoii"] = new Image();
Imagenes["nvVoii"].src = '../../FW/image/icons/nvVoii.png';
Imagenes["nv_admin"] = new Image();
Imagenes["nv_admin"].src = '../../FW/image/sistemas/nv_admin.png';
Imagenes["nv_mutual"] = new Image();
Imagenes["nv_mutual"].src = '../../FW/image/sistemas/nv_mutual.png';
Imagenes["nv_rrhh"] = new Image();
Imagenes["nv_rrhh"].src = '../../FW/image/sistemas/nv_rrhh.png';
Imagenes["nv_wiki"] = new Image();
Imagenes["nv_wiki"].src = '../../FW/image/sistemas/nv_wiki.png';
Imagenes["nv_diario"] = new Image();
Imagenes["nv_diario"].src = '../../FW/image/sistemas/nv_diario.png';
Imagenes["nv_control_lavado"] = new Image();
Imagenes["nv_control_lavado"].src = '../../FW/image/sistemas/nv_control_lavado.png';
Imagenes["nv_tarjeta"] = new Image();
Imagenes["nv_tarjeta"].src = '../../FW/image/sistemas/nv_tarjeta.png';
Imagenes["admintenelohoy"] = new Image();
Imagenes["admintenelohoy"].src = '../../FW/image/sistemas/nv_tenelohoy.png';
//----------------------------CUAD----------------------------------///
Imagenes["mensajes"] = new Image();
Imagenes["mensajes"].src = '../../FW/image/icons/mensajes.png'
Imagenes["movimientos"] = new Image();
Imagenes["movimientos"].src = '../../FW/image/icons/movimientos.png'
//----------------------------CUAD----------------------------------///

Imagenes["permiso_asignado"] = new Image();
Imagenes["permiso_asignado"].src = '../../FW/image/icons/user_add.png';
Imagenes["permiso_sin_asignar"] = new Image();
Imagenes["permiso_sin_asignar"].src = '../../FW/image/icons/user_delete2.png';
Imagenes["arbol"] = new Image();
Imagenes["arbol"].src = '../../FW/image/icons/arbol.png';
Imagenes["adjuntar"] = new Image();
Imagenes["adjuntar"].src = '../../FW/image/icons/adjuntar.png';
Imagenes["filtro"] = new Image();
Imagenes["filtro"].src = '../../FW/image/icons/filtro.png'
Imagenes["clave"] = new Image();
Imagenes["clave"].src = '../../FW/image/icons/clave.png'
Imagenes["pendientes"] = new Image();
Imagenes["pendientes"].src = '../../FW/image/icons/reporte.gif';
Imagenes["reporte1"] = new Image();
Imagenes["reporte1"].src = '../../FW/image/icons/reporte.gif';
Imagenes["help"] = new Image();
Imagenes["help"].src = '../../FW/image/icons/help.gif';
Imagenes["persona"] = new Image();
Imagenes["persona"].src = '../../FW/image/icons/user.gif';
Imagenes["imprimir"] = new Image();
Imagenes["imprimir"].src = '../../FW/image/icons/print2.gif';
Imagenes["credito"] = new Image();
Imagenes["credito"].src = '../../FW/image/icons/credito.gif';
Imagenes["credito1"] = new Image();
Imagenes["credito1"].src = '../../FW/image/icons/Dollar.png';
Imagenes["credito_editar"] = new Image();
Imagenes["credito_editar"].src = '../../FW/image/icons/credito_editar.gif';
Imagenes["credito_mas"] = new Image();
Imagenes["credito_mas"].src = '../../FW/image/icons/credito_mas.gif';
Imagenes["persona_cambiar_id"] = new Image();
Imagenes["persona_cambiar_id"].src = '../../FW/image/icons/persona_cambiar_id.gif';
Imagenes["persona_descuentos"] = new Image();
Imagenes["persona_descuentos"].src = '../../FW/image/icons/coins_delete.png';
Imagenes["mail"] = new Image();
Imagenes["mail"].src = '../../FW/image/icons/mail.gif';
Imagenes["credito_propiedades"] = new Image();
Imagenes["credito_propiedades"].src = '../../FW/image/icons/propiedades.png';
Imagenes["legajo_editar"] = new Image();
Imagenes["legajo_editar"].src = '../../FW/image/icons/legajo_editar.png';
Imagenes["comentario"] = new Image();
Imagenes["comentario"].src = '../../FW/image/icons/comentario3.png';
Imagenes["operador"] = new Image();
Imagenes["operador"].src = '../../FW/image/icons/operador.png';
Imagenes["activedirectory"] = new Image();
Imagenes["activedirectory"].src = '../../FW/image/icons/activedirectory.png';
Imagenes["seguro"] = new Image();
Imagenes["seguro"].src = '../../FW/image/icons/seguro.png';
Imagenes["mov_credito"] = new Image();
Imagenes["mov_credito"].src = '../../FW/image/icons/mov_credito.png';
Imagenes["recupero"] = new Image();
Imagenes["recupero"].src = '../../FW/image/icons/recupero.png';
Imagenes["legajo"] = new Image();
Imagenes["legajo"].src = '../../FW/image/icons/legajo.png';
Imagenes["canal"] = new Image();
Imagenes["canal"].src = '../../FW/image/icons/canal.png';
Imagenes["guia_tel"] = new Image();
Imagenes["guia_tel"].src = '../../FW/image/icons/guia_tel.png';
Imagenes["abm"] = new Image();
Imagenes["abm"].src = '../../FW/image/icons/abm.png';
Imagenes["guardar"] = new Image();
Imagenes["guardar"].src = '../../FW/image/icons/guardar.png';
Imagenes["guardar_como"] = new Image();
Imagenes["guardar_como"].src = '../../FW/image/icons/guardar_como.png';
Imagenes["foto"] = new Image();
Imagenes["foto"].src = '../../FW/image/icons/foto.png';
Imagenes["cuenta_mas"] = new Image();
Imagenes["cuenta_mas"].src = '../../FW/image/icons/cuenta_mas.gif';
Imagenes["seleccionar"] = new Image();
Imagenes["seleccionar"].src = '../../FW/image/icons/agregar_cargo.png';
Imagenes["persona_seleccionar"] = new Image();
Imagenes["persona_seleccionar"].src = '../../FW/image/icons/persona_seleccionar.gif';
Imagenes["plan_sel"] = new Image();
Imagenes["plan_sel"].src = '../../FW/image/icons/plan_seleccionar1.gif';
Imagenes["persona_sel"] = new Image();
Imagenes["persona_sel"].src = '../../FW/image/icons/persona_seleccionar.gif';
Imagenes["persona_quitar"] = new Image();
Imagenes["persona_quitar"].src = '../../FW/image/icons/persona_quitar.gif';
Imagenes["descuento_saldo"] = new Image();
Imagenes["descuento_saldo"].src = '../../FW/image/icons/descuento_saldo.gif';
Imagenes["descuento_mas"] = new Image();
Imagenes["descuento_mas"].src = '../../FW/image/icons/descuento_mas.gif';
Imagenes["procesos"] = new Image();
Imagenes["procesos"].src = '../../FW/image/icons/procesos.gif';
Imagenes["servidor"] = new Image();
Imagenes["servidor"].src = '../../FW/image/icons/servidor.png';
Imagenes["sistema"] = new Image();
Imagenes["sistema"].src = '../../FW/image/sistemas/sistema.png';
Imagenes["rh_buscar"] = new Image();
Imagenes["rh_buscar"].src = '../../FW/image/icons/buscar.png';
Imagenes["password"] = new Image();
Imagenes["password"].src = '../../FW/image/icons/candado.png';
Imagenes["folder"] = new Image();
Imagenes["folder"].src = '../../FW/image/icons/folder.png';
Imagenes["cancelar"] = new Image();
Imagenes["cancelar"].src = '../../FW/image/icons/cancelar.png';
Imagenes["servicio"] = new Image();
Imagenes["servicio"].src = '../../FW/image/icons/servicio.png';
Imagenes["servicio_buscar"] = new Image();
Imagenes["servicio_buscar"].src = '../../FW/image/icons/servicio_buscar.png';
Imagenes["servicio_asignar"] = new Image();
Imagenes["servicio_asignar"].src = '../../FW/image/icons/servicio_asignar.png';
Imagenes["plan"] = new Image();
Imagenes["plan"].src = '../../FW/image/icons/plan.png';
Imagenes["entidad"] = new Image();
Imagenes["entidad"].src = '../../FW/image/icons/entidad.png';
Imagenes["entidad_grupo"] = new Image();
Imagenes["entidad_grupo"].src = '../../FW/image/icons/entidad_grupo.png';
Imagenes["cheque"] = new Image();
Imagenes["cheque"].src = '../../FW/image/icons/cheque.png';
Imagenes["nota_revision"] = new Image();
Imagenes["nota_revision"].src = '../../FW/image/icons/nota_revision.png';
Imagenes["nota_inspeccion"] = new Image();
Imagenes["nota_inspeccion"].src = '../../FW/image/icons/servicio_buscar.png';
Imagenes["edicion"] = new Image();
Imagenes["edicion"].src = '../../FW/image/icons/edicion.png';
Imagenes["publicacion"] = new Image();
Imagenes["publicacion"].src = '../../FW/image/icons/publicacion.png';
Imagenes["cambio_estado"] = new Image();
Imagenes["cambio_estado"].src = '../../FW/image/icons/cambio_estado.png';
Imagenes["parametros"] = new Image();
Imagenes["parametros"].src = '../../FW/image/icons/parametros.png';

Imagenes['estructura'] = new Image();
Imagenes['estructura'].src = '../../FW/image/icons/tree.gif';
Imagenes['indice'] = new Image();
Imagenes['indice'].src = '../../FW/image/icons/tree.gif';
Imagenes['buscar'] = new Image();
Imagenes['buscar'].src = '../../FW/image/icons/buscar.png';
Imagenes['cerrar'] = new Image();
Imagenes['cerrar'].src = '../../FW/image/icons/eliminar.png';
Imagenes['trabajo'] = new Image();
Imagenes['trabajo'].src = '../../FW/image/icons/trabajo.png';
Imagenes['empresa'] = new Image();
Imagenes['empresa'].src = '../../FW/image/icons/empresa.png';
Imagenes['sector'] = new Image();
Imagenes['sector'].src = '../../FW/image/icons/sector.png';
Imagenes['ref'] = new Image();
Imagenes['ref'].src = '../../FW/image/icons/info.png';
Imagenes['actualizar'] = new Image();
Imagenes['actualizar'].src = '../../FW/image/icons/refresh.png';
Imagenes['pagina_impresion'] = new Image();
Imagenes['pagina_impresion'].src = '../../FW/image/icons/pagina_impresion.png';
Imagenes['exit'] = new Image();
Imagenes['exit'].src = '../../FW/image/icons/exit.png';
Imagenes['subir'] = new Image();
Imagenes['subir'].src = '../../FW/image/icons/subir.png';
Imagenes['bajar'] = new Image();
Imagenes['bajar'].src = '../../FW/image/icons/bajar.png';
Imagenes['eliminar'] = new Image();
Imagenes['eliminar'].src = '../../FW/image/icons/eliminar.png';
Imagenes['agregar1'] = new Image();
Imagenes['agregar1'].src = '../../FW/image/icons/agregar.png';
Imagenes['cuenta'] = new Image();
Imagenes['cuenta'].src = '../../FW/image/icons/cuenta.png';
Imagenes["periodo"] = new Image();
Imagenes["periodo"].src = '../../FW/image/icons/periodo.png';
Imagenes["abierto"] = new Image();
Imagenes["abierto"].src = '../../FW/image/icons/abierto.png';
Imagenes["cerrado"] = new Image();
Imagenes["cerrado"].src = '../../FW/image/icons/cerrar.png';
Imagenes['ayuda'] = new Image();
Imagenes['ayuda'].src = '../../FW/image/icons/ayuda.png';
Imagenes['default'] = new Image();
Imagenes['default'].src = '../../FW/image/icons/user.gif';
Imagenes['hoja'] = new Image();
Imagenes['hoja'].src = '../../FW/image/icons/nueva.png';
Imagenes['Desconocida'] = new Image();
Imagenes['Desconocida'].src = '../../FW/image/icons/user.gif';

Imagenes['registro'] = new Image();
Imagenes['registro'].src = '../../FW/image/icons/registro.gif';
Imagenes['registro_mas'] = new Image();
Imagenes['registro_mas'].src = '../../FW/image/icons/registro_mas.gif';
Imagenes['registro_mas2'] = new Image();
Imagenes['registro_mas2'].src = '../../FW/image/icons/registro_mas2.gif';
Imagenes['registro_editar'] = new Image();
Imagenes['registro_editar'].src = '../../FW/image/icons/registro_editar.gif';
Imagenes['down'] = new Image();
Imagenes['down'].src = '../../FW/image/icons/down.gif';
Imagenes['up'] = new Image();
Imagenes['up'].src = '../../FW/image/icons/up.gif';
Imagenes['upload'] = new Image();
Imagenes['upload'].src = '../../FW/image/icons/upload.png';

Imagenes['carta'] = new Image();
Imagenes['carta'].src = '../../FW/image/icons/script.png';
Imagenes['analisis'] = new Image();
Imagenes['analisis'].src = '../../FW/image/icons/analisis.png';
Imagenes['catalogo'] = new Image();
Imagenes['catalogo'].src = '../../FW/image/icons/Catalogo.gif';
Imagenes['agregar'] = new Image();
Imagenes['agregar'].src = '../../FW/image/icons/seleccionar.gif';
Imagenes['modulo'] = new Image();
Imagenes['modulo'].src = '../../FW/image/icons/modulo.png';
Imagenes['login'] = new Image();
Imagenes['login'].src = '../../FW/image/icons/login.png';
Imagenes['permiso'] = new Image();
Imagenes['permiso'].src = '../../FW/image/icons/permiso.png';


 Imagenes["interbanking"] = new Image();
 Imagenes["interbanking"].src = '../../FW/image/icons/interbanking.png';
 Imagenes["inicio"] = new Image();
 Imagenes["inicio"].src = '../../FW/image/icons/home.png';
 Imagenes['herramientas'] = new Image();
 Imagenes['herramientas'].src = '../../FW/image/icons/herramientas.png';
 Imagenes["adminreporte"] = new Image();
 Imagenes["adminreporte"].src = '../../FW/image/icons/adminreporte.png';
 Imagenes["reporte"] = new Image();
 Imagenes["reporte"].src = '../../FW/image/icons/reporte.png';
 Imagenes["comb_pendientes"] = new Image();
 Imagenes["comb_pendientes"].src = '../../FW/image/icons/comprobantes_pendientes.png';
 Imagenes["procesar"] = new Image();
 Imagenes["procesar"].src = '../../FW/image/icons/procesar.png';
 Imagenes["envios"] = new Image();
 Imagenes["envios"].src = '../../FW/image/icons/envios.png';
 Imagenes["envios_finalizados"] = new Image();
 Imagenes["envios_finalizados"].src = '../../FW/image/icons/envios_finalizados.png';
 Imagenes["envios_pendientes"] = new Image();
 Imagenes["envios_pendientes"].src = '../../FW/image/icons/envios_pendientes.png';
 Imagenes["pagos"] = new Image();
 Imagenes["pagos"].src = '../../FW/image/icons/pagos.png';
 Imagenes["pagos1"] = new Image();
 Imagenes["pagos1"].src = '../../FW/image/icons/pagos1.png';
 Imagenes["pagos2"] = new Image();
 Imagenes["pagos2"].src = '../../FW/image/icons/money_add.png';
 Imagenes["pago_voluntario"] = new Image();
 Imagenes["pago_voluntario"].src = '../../FW/image/icons/pago_voluntario.png';
 Imagenes["tablas"] = new Image();
 Imagenes["tablas"].src = '../../FW/image/icons/tablas.png';
 Imagenes["persona_sel"] = new Image();
 Imagenes["persona_sel"].src = '../../FW/image/icons/personas.png';
 Imagenes['modulo'] = new Image();
 Imagenes['modulo'].src = '../../FW/image/icons/modulo.png';
 Imagenes["editar"] = new Image();
 Imagenes["editar"].src = '../../FW/image/icons/editar.png';
 Imagenes["buscar_doc"] = new Image();
 Imagenes["buscar_doc"].src = '../../FW/image/icons/buscar_doc.png';
 Imagenes["socio"] = new Image();
 Imagenes["socio"].src = '../../FW/image/icons/socio.png';
 Imagenes["socio_alta"] = new Image();
 Imagenes["socio_alta"].src = '../../FW/image/icons/socio_alta.png';
 Imagenes["socio_baja"] = new Image();
 Imagenes["socio_baja"].src = '../../FW/image/icons/socio_baja.png';
 Imagenes["periodicidad"] = new Image();
 Imagenes["periodicidad"].src = '../../FW/image/icons/periodicidad.png';
 Imagenes["excel"] = new Image();
 Imagenes["excel"].src = '../../FW/image/icons/excel.png';
 Imagenes["pdf"] = new Image();
 Imagenes["pdf"].src = '../../FW/image/icons/file_pdf.png';
 
 Imagenes["mas"] = new Image();
 Imagenes["mas"].src = '../../FW/image/icons/mas.jpg';
 Imagenes["menos"] = new Image();
 Imagenes["menos"].src = '../../FW/image/icons/menos.jpg';
 Imagenes["punto"] = new Image();
 Imagenes["punto"].src = '../../FW/image/icons/punto.jpg';
 Imagenes["persona_mas"] = new Image();
 Imagenes["persona_mas"].src = '../../FW/image/icons/persona_mas.gif';
 Imagenes["persona_editar"] = new Image();
 Imagenes["persona_editar"].src = '../../FW/image/icons/persona_editar.gif';
 Imagenes["imprimir"] = new Image();
 Imagenes["imprimir"].src = '../../FW/image/icons/imprimir.png';
 Imagenes["printer"] = new Image();
 Imagenes["printer"].src = '../../FW/image/icons/printer.png';
 Imagenes['nueva'] = new Image();
 Imagenes['nueva'].src = '../../FW/image/icons/nueva.png';
 Imagenes['browser_img'] = new Image();
 Imagenes['browser_img'].src = '../../FW/image/icons/browser_img.png';
 Imagenes['explorer'] = new Image();
 Imagenes['explorer'].src = '../../FW/image/icons/explorer.png';
 Imagenes['cable'] = new Image();
 Imagenes['cable'].src = '../../FW/image/icons/download_txt.png';
 
 Imagenes["hoy"] = new Image();
 Imagenes["hoy"].src = '../../FW/image/icons/hoy.png';
 Imagenes["dia"] = new Image();
 Imagenes["dia"].src = '../../FW/image/icons/dia.png';
 Imagenes["semana"] = new Image();
 Imagenes["semana"].src = '../../FW/image/icons/semana.png';
 Imagenes["mes"] = new Image();
 Imagenes["mes"].src = '../../FW/image/icons/mes.png';
 Imagenes['contactos'] = new Image();
 Imagenes['contactos'].src = '../../FW/image/icons/contactos2.ico';
 Imagenes["telefono01"] = new Image();
 Imagenes["telefono01"].src = '../../FW/image/icons/telefono2.png'; 
  
 Imagenes["vincular"] = new Image();
 Imagenes["vincular"].src = '../../FW/image/icons/vincular.png';
 Imagenes["desvincular"] = new Image();
 Imagenes["desvincular"].src = '../../FW/image/icons/desvincular.png';
 
 Imagenes["trabajo_mas"] = new Image();
 Imagenes["trabajo_mas"].src = '../../FW/image/icons/trabajo_mas.gif';
 Imagenes["trabajo"] = new Image();
 Imagenes["trabajo"].src = '../../FW/image/icons/trabajo.png';
 Imagenes["bica"] = new Image();
 Imagenes["bica"].src = '../../FW/image/icons/bica.png';
 Imagenes["abm1"] = new Image();
 Imagenes["abm1"].src = '../../FW/image/icons/abm1.png';
 Imagenes["bejerman"] = new Image();
 Imagenes["bejerman"].src = '../../FW/image/icons/bejerman.png';
 Imagenes["bloqueo"] = new Image();
 Imagenes["bloqueo"].src = '../../FW/image/icons/bloqueo.png';
 Imagenes["mapa"] = new Image();
 Imagenes["mapa"].src = '../../FW/image/icons/mapa_ico.gif';
 Imagenes["libro"] = new Image();
 Imagenes["libro"].src = '../../FW/image/icons/libro.png';
 Imagenes["persona_add"] = new Image();
 Imagenes["persona_add"].src = '../../FW/image/icons/user_add.png';
 Imagenes["persona_edit"] = new Image();
 Imagenes["persona_edit"].src = '../../FW/image/icons/user_edit.png';
 Imagenes["persona_go"] = new Image();
 Imagenes["persona_go"].src = '../../FW/image/icons/user_go.png';
 Imagenes["cobro"] = new Image();
 Imagenes["cobro"].src = '../../FW/image/icons/coins_in_hand.png';
 Imagenes["cta_banco"] = new Image();
 Imagenes["cta_banco"].src = '../../FW/image/icons/bank.png';
 Imagenes["estado"] = new Image();
 Imagenes["estado"].src = '../../FW/image/icons/folder_go.png';
 Imagenes["control_calidad"] = new Image();
 Imagenes["control_calidad"].src = '../../FW/image/icons/control_calidad.png';
 Imagenes["cobranzas"] = new Image();
 Imagenes["cobranzas"].src = '../../FW/image/icons/business.gif';
 Imagenes["muper"] = new Image();
 Imagenes["muper"].src = '../../FW/image/icons/logo_muper.png';
 Imagenes['auto_run'] = new Image();
 Imagenes['auto_run'].src = '../../FW/image/icons/auto_run.png';

 //LINKS a otras aplicaciones 
 Imagenes['sidecreer'] = new Image();
 Imagenes['sidecreer'].src = '../../FW/image/icons/links/sidecreer16x16.png'
 Imagenes['anses'] = new Image();
 Imagenes['anses'].src = '../../FW/image/icons/links/anses.png'
 Imagenes['telecom'] = new Image();
 Imagenes['telecom'].src = '../../FW/image//icons/links/telecom.png'
 Imagenes['nosis'] = new Image();
 Imagenes['nosis'].src = '../../FW/image/icons/links/nosis.png'
 Imagenes['bcra'] = new Image();
 Imagenes['bcra'].src = '../../FW/image/icons/links/bcra.png'
 Imagenes['ie'] = new Image();
 Imagenes['ie'].src = '../../FW/image/icons/links/ie.png'
 
 //wiki tarea
 
 Imagenes['period_origen'] = new Image();
 Imagenes['period_origen'].src = '../../FW/image/icons/periodicidad_origen.png';
 Imagenes['guardar_cerrar'] = new Image();
 Imagenes['guardar_cerrar'].src = '../../FW/image/icons/guardar_cerrar.png';
 Imagenes['play'] = new Image();
 Imagenes['play'].src = '../../FW/image/icons/play.png';
 
  //Diario

 Imagenes['comprobante'] = new Image();
 Imagenes['comprobante'].src = '../../FW/image/icons/modulo2.ico';
 Imagenes['factura'] = new Image();
 Imagenes['factura'].src = '../../FW/image/icons/guita.ico';
 Imagenes['contacto'] = new Image();
 Imagenes['contacto'].src = '../../FW/image/icons/grupo.png';
 Imagenes['confirmar'] = new Image();
 Imagenes['confirmar'].src = '../../FW/image/icons/confirmar.png';
 Imagenes['nuevo'] = new Image();
 Imagenes['nuevo'].src = '../../FW/image/icons/file.png';
 Imagenes["editar_rubro"] = new Image();
 Imagenes["editar_rubro"].src = '../../FW/image/icons/edit-3.ico';
 Imagenes["eliminar_rubro"] = new Image();
 Imagenes["eliminar_rubro"].src = '../../FW/image/icons/eliminar1.png'
 Imagenes["anular_comprobante"] = new Image();
 Imagenes["anular_comprobante"].src = '../../FW/image/icons/sinlegajo1.png'
 Imagenes['copiar'] = new Image();
 Imagenes['copiar'].src = '../../FW/image/icons/copiar.png';
 
 
 //Lavado
 Imagenes["alerta"] = new Image();
 Imagenes["alerta"].src = '../../FW/image/icons/alerta.png';
 
 
 //RRHH 
Imagenes["imprimir2"] = new Image();
Imagenes["imprimir2"].src = '../../FW/image/icons/imprimir.png';
Imagenes["asignar"] = new Image();
Imagenes["asignar"].src = '../../FW/image/icons/asignar.png';
Imagenes["confirmar"] = new Image();
Imagenes["confirmar"].src = '../../FW/image/icons/activo.png';
Imagenes["confirmar_det"] = new Image();
Imagenes["confirmar_det"].src = '../../FW/image/icons/agregar_cargo.png';
Imagenes["agregar_novedad"] = new Image();
Imagenes["agregar_novedad"].src = '../../FW/image/icons/agregar_novedad.png';


//SICA
Imagenes["dependencia"] = new Image();
Imagenes["dependencia"].src = '../../FW/image/icons/agregar_novedad.png';
Imagenes['script'] = new Image();
Imagenes['script'].src = '../../FW/image/icons/script.png';
Imagenes["pasajes"] = new Image();
Imagenes["pasajes"].src = '../../FW/image/icons/modulo5.ico';
Imagenes["aplicarCambios"] = new Image();
Imagenes["aplicarCambios"].src = '../../FW/image/icons/abierto1.png';
Imagenes["asignarModulo"] = new Image();
Imagenes["asignarModulo"].src = '../../FW/image/icons/asignar.png';
Imagenes["genPasaje"] = new Image();
Imagenes["genPasaje"].src = '../../FW/image/icons/arbol.ico';
Imagenes["controlInteg"] = new Image();
Imagenes["controlInteg"].src = '../../FW/image/icons/control_calidad.png';
Imagenes["exportar"] = new Image();
Imagenes["exportar"].src = '../../FW/image/icons/bajar.png';
Imagenes["importar"] = new Image();
Imagenes["importar"].src = '../../FW/image/icons/returndoc.gif';
Imagenes["pasaje_dependencia"] = new Image();
Imagenes["pasaje_dependencia"].src = '../../FW/image/icons/planes.gif';


